### ISSUE TITLE
diff page using "new" fonts

### ISSUE THREAD

**Issue by JamesHutchison** [rreusser/the-old-github-font#9]
Thank you for making this.

On the diff page using Mac OS X El Capitan, using the latest version of chrome, it looks like the "new" (unaltered) fonts are still being used.

Thanks!

**Comment by rreusser** [comment]
Thanks for the report! I'll check on this when I get a chance.

**Comment by rreusser** [comment]
Update: actually, this fun extension has kinda scratched the itch for me and I think it's time to move on with life (if that's possible! oh! the letter-spacing!) and gladly accept PRs but not really expand it too much otherwise. So I really appreciate the feedback and if you have a solution, I'll gladly merge it, but otherwise I probably won't pursue this. Thanks for the interest! 👍

**Comment by rreusser** [comment]
Really appreciate the PR. Thanks!
